In [2]:
def a():
    
    print("Hi this is a ")

a()

Hi this is a 


In [4]:
class a:
    def a_method():
        print("Hi this is a method from class a")

b = a()
a.a_method()

Hi this is a method from class a


In [7]:
def test():
    print("Hi this is a test!!")

if __name__ == "__main__":
    test()

Hi this is a test!!


In [2]:
x = lambda a,b:a*b/2

print(x(10,20))

100.0


In [9]:
def myfunc(n):
    return lambda a:a*n

doubleme = myfunc(10)
print(doubleme(2))

20


In [10]:
def mySecondFunction(a,b,c):
    
    return lambda x:(a+b+c)/x

myThirdFunction = mySecondFunction(10,20,20)
    

In [11]:
print(myThirdFunction(2))

25.0


In [16]:
f = open("demo.txt","r")
print(f.readline())
print(f.readline())
print(f.readline())
print(f.readline())

Hi from Hari

Hi from Sai

Hi from Shiv

Hi from Krithi


In [18]:
f = open("demo.txt","r")
print(f.read())

Hi from Hari
Hi from Sai
Hi from Shiv
Hi from Krithi


In [19]:
f = open("demo.txt","r")
print(f.read(10))

Hi from Ha


In [20]:
f = open("demo.txt","r")
for x in f:
    print(x)


Hi from Hari

Hi from Sai

Hi from Shiv

Hi from Krithi


In [32]:
f = open("demo.txt","a")
f.write(" \r Hi from Hari")
f.write(" \r Hi from Shiv ")
f.write(" \r Hi from Sai")
f.write(" \r Hi from Krithi")

f1 = open("demo.txt","r")

for x in f1:
    print(x)


 

 Hi from Hari 

 Hi from Shiv  

 Hi from Sai 

 Hi from Krithi 

 Hi from Hari 

 Hi from Shiv  

 Hi from Sai 

 Hi from Krithi 

 Hi from Hari 

 Hi from Shiv  

 Hi from Sai 

 Hi from Krithi


In [3]:
import numpy as np

a = np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]


In [8]:
from numerology import Pythagorean

num = Pythagorean(first_name="Barack", last_name="Obama", birthdate="1961-08-04", verbose=False)
print(num.key_figures)

{'first_name': 'Barack', 'last_name': 'Obama', 'hearth_desire_number': 1, 'personality_number': 22, 'destiny_number': 5, 'expression_number': 5, 'active_number': 9, 'legacy_number': 5, 'full_name_numbers': {1: 4, 2: 3, 9: 1, 3: 1, 6: 1, 4: 1}, 'full_name_missing_numbers': (5, 7, 8), 'birthdate': '1961-08-04', 'life_path_number': 2, 'life_path_number_alternative': 2, 'birthdate_day_num': 4, 'birthdate_month_num': 8, 'birthdate_year_num': 8, 'birthdate_year_num_alternative': 7, 'power_number': 7, 'power_number_alternative': 7}


In [9]:
import numpy as np

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
import numpy as np

a= np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
import numpy as np

np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [14]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [15]:
np.arange(10,20,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [17]:
np.arange(1,10,5)

array([1, 6])

In [18]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
import numpy as np

def generate_numbers_between(x, y, z):
    if z <= 0:
        return np.array([])
    
    # Generate z numbers between x and y
    numbers = np.linspace(x, y, z)
    
    return numbers

# Example usage:
x = 1
y = 10
z = 5
result = generate_numbers_between(x, y, z)
print("Generated numbers between", x, "and", y, ":", result)

Generated numbers between 1 and 10 : [ 1.    3.25  5.5   7.75 10.  ]


In [22]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [24]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

## Filling Random Number


In [26]:
np.random.random((2,3))

array([[0.94211657, 0.82173511, 0.54483966],
       [0.03138861, 0.83583729, 0.61156286]])

In [28]:
np.random.random((2,3))

array([[0.65657161, 0.03378585, 0.83969283],
       [0.03938763, 0.71023053, 0.07817824]])

In [32]:
a = np.random.randint(1,10,5)
print(a)
print(np.shape(a))

[9 8 6 7 2]
(5,)


In [31]:
a = np.array([[2,3,4],[5,6,7]])
np.shape(a)

(2, 3)

In [38]:
a = np.array([[2,3,4],[5,6,7]])
a.shape = (3,2)
print(a)

[[2 3]
 [4 5]
 [6 7]]


In [40]:
a = np.arange(24)
print(a.dtype)
print(a)

int64
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [41]:
import numpy as np

np.sum([10,20])

30

In [43]:
import numpy as np
a,b,c,d,e = 10,20,30,40,50

np.sum([a,b,c])

60

In [45]:
np.sum([[1,2],[5,6]])

14

In [49]:
a = [[1,2],[5,6]]
print(a)

np.sum(a,axis=1)

[[1, 2], [5, 6]]


array([ 3, 11])

In [52]:
a = [[1,2],[5,6]]
b = [[1,2],[5,6]]
print(a)

np.multiply(a,b)

[[1, 2], [5, 6]]


array([[ 1,  4],
       [25, 36]])

In [55]:
import numpy as np

# Example array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Multiply two arrays 
result_array_mul = arr * arr

# Multiply each element by the sum of its row (along columns)
result_row_div = arr * arr.sum(axis=1)[:, np.newaxis]

# Multiply each element by the sum of its column (along rows)
result_col_div = arr * arr.sum(axis=0)

print("Result of plain array multiplication:")
print(result_array_mul)


print("Result of element-wise division along rows:")
print(result_row_div)
print("\nResult of element-wise division along columns:")
print(result_col_div)


Result of plain array multiplication:
[[ 1  4  9]
 [16 25 36]]
Result of element-wise division along rows:
[[ 6 12 18]
 [60 75 90]]

Result of element-wise division along columns:
[[ 5 14 27]
 [20 35 54]]


In [57]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [63]:
np.arange(16).reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [65]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [77]:
import numpy as np

x = np.arange(16).reshape(4,4)
print("\n \ n Before Spliting actual array",x)

#print("\n \ n After Spliting  array by 2 ")
#np.hsplit(x,2)

print("\n \ n After Spliting  array by 3   ")
np.hsplit(x,np.array([3]))

print("\n \ n After Spliting  array by 3 , 6  ")
np.hsplit(x,np.array([4,8]))


 \ n Before Spliting actual array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 \ n After Spliting  array by 3   

 \ n After Spliting  array by 3 , 6  


[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([], shape=(4, 0), dtype=int64),
 array([], shape=(4, 0), dtype=int64)]

In [81]:
import numpy as np

x = np.arange(16).reshape(4,4)

print(x,"\n \n")
#print(np.hsplit(x,2),"\n \n")
print(np.hsplit(x,np.array([3])),"\n \n")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 
 

[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])] 
 



In [84]:
import numpy as np
import sys

#define a list

l = range(1000)

print("Size of list",sys.getsizeof(1)*len(l))

#define a numpy array
a = np.arange(1000)
print("Size of numpy array",a.size * a.itemsize)


Size of list 28000
Size of numpy array 8000


In [88]:
import time 

def using_list():
    t1 = time.time()
    
    X = range(10000)
    Y = range(10000)
    
    Z = [X[i]+Y[i] for i in range(len(x))]
    return time.time() - t1

def using_numpy():
    t1 = time.time()
    
    X = np.arange(10000)
    Y = np.arange(10000)
    Z = X+Y
    return time.time() - t1

if __name__ == "__main__":
    print("using list",using_list())
    print("using numpy",using_numpy())

using list 5.9604644775390625e-06
using numpy 0.0006289482116699219


In [90]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])


result_multiply_columns = np.prod(arr, axis=1)
print("Multiply along rows:", result_multiply_columns)

result_multiply_rows = np.prod(arr, axis=0)
print("Multiply along columns:", result_multiply_rows)

Multiply along rows: [  6 120 504]
Multiply along columns: [ 28  80 162]


In [92]:
import numpy as np

x = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

y = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

result = x * y

print("result ",result)

result  [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
